### ISSUE TITLE
firstboot does not work / how to properly reset the device

### ISSUE THREAD

**Issue by dragetd** [brunompena/zsun-resources#1]
When in recovery, using `mount_firmware` mounts it under /firmware. The command `firstboot` (which just calls jffs2reset) assumes to find the system to reset under /dev/mdt6, but it is /dev/mdt10.

I am not familiar enough with all details and am not sure how to manually reformat the device… I'd like to start fresh and reset the device.

**Comment by brunompena** [comment]
**Please use the [OpenWrt forums](https://forum.openwrt.org/t/supporting-zsun-wifi-card-reader-16mb-flash-64mb-ram-ar9331) for support.**

OpenWrt is completely unaware of this "recovery" concept and therefore none of its tools is capable of targeting an OpenWrt installation other than one that is currently running.

To reset your main firmware you can go with either one of the following approaches:

- Mount the main firmware using the [mount_firmware](https://github.com/brunompena/mount_firmware) script and then remove all content from `/firmware/overlay/upper/`
    ```
    mount_firmware
    rm -rf /firmware/overlay/upper/*
    umount_firmware
    ```

- Reflash the firmware partition
    ```
    mtd write /tmp/openwrt-ath79-generic-zsun_sd100-squashfs-sysupgrade.bin firmware
    ```
